language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: $UPLOAD_DIR
  fqdn: $CUSTOM_DOMAIN
branches:
  only:
    - master
